BEGIN;
INSERT INTO classe VALUES (1, 'cosmetiques, parfums');
INSERT INTO classe VALUES (2, 'electronique');
INSERT INTO classe VALUES (3, 'chimie');
INSERT INTO classe VALUES (4, 'aliments');
INSERT INTO classe VALUES (5, 'mecanique, machine_outils');
INSERT INTO classe VALUES (6, 'logiciels');
INSERT INTO classe VALUES (7, 'automobiles');
INSERT INTO classe VALUES (8, 'aeronautique');
INSERT INTO classe VALUES (9, 'textiles');
INSERT INTO classe VALUES (10, 'pharmacie, genie genetique');
INSERT INTO classe VALUES (11, 'vetements, accessoires');
INSERT INTO classe VALUES (12, 'imprimerie');
INSERT INTO classe VALUES (13, 'cinema, radio, television');
INSERT INTO classe VALUES (14, 'publicite, affichage');
INSERT INTO classe VALUES (15, 'bureautique');
INSERT INTO classe VALUES (16, 'materiel medical');
INSERT INTO classe VALUES (17, 'hydraulique');
INSERT INTO classe VALUES (18, 'agriculture');
INSERT INTO classe VALUES (19, 'batiment, travaux-publics');
INSERT INTO classe VALUES (20, 'juridique');
INSERT INTO classe VALUES (21, 'sante');
INSERT INTO classe VALUES (22, 'hotellerie, tourisme');
INSERT INTO classe VALUES (23, 'commercial');
INSERT INTO classe VALUES (24, 'petro-chimie');



--
-- TOC entry 3167 (class 0 OID 16554)
-- Dependencies: 197
-- Data for Name: enr; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO enr VALUES (1, 1100, 'US', 1, '2012-02-02');
INSERT INTO enr VALUES (19, 22200, 'US', 46, '2020-11-01');
INSERT INTO enr VALUES (20, 32500, 'US', 46, '2021-01-01');
INSERT INTO enr VALUES (45, 72510, 'US', 28, '2025-01-01');
INSERT INTO enr VALUES (67, 170550, 'US', 28, '2035-01-01');
INSERT INTO enr VALUES (21, 308500, 'US', 46, '2050-01-01');
INSERT INTO enr VALUES (48, 309610, 'US', 20, '2050-01-01');
INSERT INTO enr VALUES (28, 410501, 'US', 46, '2067-01-01');
INSERT INTO enr VALUES (41, 425561, 'US', 28, '2068-04-01');
INSERT INTO enr VALUES (72, 440931, 'US', 27, '1970-05-10');
INSERT INTO enr VALUES (3, 520550, 'US', 1, '1978-02-02');
INSERT INTO enr VALUES (4, 530575, 'US', 46, '1979-02-02');
INSERT INTO enr VALUES (77, 530679, 'US', 27, '1979-02-02');
INSERT INTO enr VALUES (2, 620200, 'US', 1, '1982-03-01');
INSERT INTO enr VALUES (32, 630200, 'US', 47, '1983-03-01');
INSERT INTO enr VALUES (85, 630310, 'US', 21, '1983-04-01');
INSERT INTO enr VALUES (54, 632405, 'US', 9, '1983-04-01');
INSERT INTO enr VALUES (37, 652505, 'US', 26, '1988-04-01');
INSERT INTO enr VALUES (63, 700250, 'US', 28, '1990-05-01');
INSERT INTO enr VALUES (58, 731220, 'US', 9, '1993-01-01');
INSERT INTO enr VALUES (13, 11000, 'DE', 1, '2012-02-02');
INSERT INTO enr VALUES (25, 22200, 'DE', 46, '2020-11-01');
INSERT INTO enr VALUES (26, 32600, 'DE', 46, '2021-01-01');
INSERT INTO enr VALUES (46, 73510, 'DE', 20, '2025-01-01');
INSERT INTO enr VALUES (68, 171551, 'DE', 24, '2035-01-01');
INSERT INTO enr VALUES (49, 309330, 'DE', 20, '2050-02-01');
INSERT INTO enr VALUES (29, 411567, 'DE', 48, '2067-01-01');
INSERT INTO enr VALUES (42, 426589, 'DE', 26, '2068-04-01');
INSERT INTO enr VALUES (73, 441990, 'DE', 27, '1970-05-10');
INSERT INTO enr VALUES (15, 521570, 'DE', 1, '1978-02-02');
INSERT INTO enr VALUES (17, 521571, 'DE', 1, '1978-02-02');
INSERT INTO enr VALUES (16, 531575, 'DE', 46, '1979-02-02');
INSERT INTO enr VALUES (78, 530678, 'DE', 27, '1979-02-02');
INSERT INTO enr VALUES (14, 625600, 'DE', 1, '1982-03-01');
INSERT INTO enr VALUES (33, 631400, 'DE', 47, '1983-03-01');
INSERT INTO enr VALUES (86, 634310, 'DE', 21, '1983-04-01');
INSERT INTO enr VALUES (55, 635444, 'DE', 9, '1983-04-01');
INSERT INTO enr VALUES (38, 652505, 'DE', 26, '1988-04-01');
INSERT INTO enr VALUES (64, 701250, 'DE', 20, '1990-05-01');
INSERT INTO enr VALUES (9, 11100, 'UK', 1, '2012-02-02');
INSERT INTO enr VALUES (81, 23200, 'UK', 46, '2020-11-01');
INSERT INTO enr VALUES (82, 32600, 'UK', 46, '2021-01-01');
INSERT INTO enr VALUES (69, 171551, 'UK', 24, '2035-01-01');
INSERT INTO enr VALUES (83, 300700, 'UK', 46, '2050-01-01');
INSERT INTO enr VALUES (50, 306330, 'UK', 20, '2050-02-01');
INSERT INTO enr VALUES (30, 412567, 'UK', 48, '2067-01-01');
INSERT INTO enr VALUES (43, 426449, 'UK', 26, '2068-04-01');
INSERT INTO enr VALUES (74, 441990, 'UK', 27, '1970-05-10');
INSERT INTO enr VALUES (11, 522570, 'UK', 1, '1978-02-02');
INSERT INTO enr VALUES (12, 531675, 'UK', 46, '1979-02-02');
INSERT INTO enr VALUES (79, 530678, 'UK', 27, '1979-02-02');
INSERT INTO enr VALUES (10, 625700, 'UK', 1, '1982-03-01');
INSERT INTO enr VALUES (34, 632400, 'UK', 47, '1983-03-01');
INSERT INTO enr VALUES (87, 634510, 'UK', 21, '1983-04-01');
INSERT INTO enr VALUES (56, 636484, 'UK', 9, '1983-04-01');
INSERT INTO enr VALUES (39, 653605, 'UK', 26, '1988-04-01');
INSERT INTO enr VALUES (65, 701350, 'UK', 20, '1990-05-01');
INSERT INTO enr VALUES (60, 731250, 'UK', 9, '1993-05-01');
INSERT INTO enr VALUES (5, 11101, 'FR', 1, '2012-02-02');
INSERT INTO enr VALUES (22, 23201, 'FR', 46, '2020-11-01');
INSERT INTO enr VALUES (23, 32601, 'FR', 46, '2021-01-01');
INSERT INTO enr VALUES (44, 73511, 'FR', 20, '2025-01-01');
INSERT INTO enr VALUES (66, 171555, 'FR', 24, '2035-01-01');
INSERT INTO enr VALUES (24, 300700, 'FR', 46, '2050-01-01');
INSERT INTO enr VALUES (47, 306361, 'FR', 20, '2050-02-01');
INSERT INTO enr VALUES (27, 412568, 'FR', 48, '2067-01-01');
INSERT INTO enr VALUES (40, 426440, 'FR', 26, '2068-04-01');
INSERT INTO enr VALUES (71, 443990, 'FR', 27, '1970-05-10');
INSERT INTO enr VALUES (7, 522572, 'FR', 1, '1978-02-02');
INSERT INTO enr VALUES (8, 534675, 'FR', 46, '1979-02-02');
INSERT INTO enr VALUES (76, 534678, 'FR', 27, '1979-02-02');
INSERT INTO enr VALUES (6, 625900, 'FR', 1, '1982-03-01');
INSERT INTO enr VALUES (31, 635400, 'FR', 47, '1983-03-01');
INSERT INTO enr VALUES (84, 636510, 'FR', 21, '1983-04-01');
INSERT INTO enr VALUES (53, 637484, 'FR', 14, '1983-04-01');
INSERT INTO enr VALUES (36, 653605, 'FR', 26, '1988-04-01');
INSERT INTO enr VALUES (62, 701350, 'FR', 20, '1990-05-01');
INSERT INTO enr VALUES (61, 731290, 'FR', 9, '1993-05-01');
INSERT INTO enr VALUES (89, 720402, 'MX', 31, '1992-05-01');


--
-- TOC entry 3168 (class 0 OID 16557)
-- Dependencies: 198
-- Data for Name: marque; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO marque VALUES (1, 'Coca Cola', 4, 'US', 1);
INSERT INTO marque VALUES (2, 'Coca Cola Light', 4, 'US', 1);
INSERT INTO marque VALUES (3, 'Coke', 4, 'US', 1);
INSERT INTO marque VALUES (4, 'Sprite', 4, 'US', 1);
INSERT INTO marque VALUES (5, 'Coca Cola', 4, 'FR', 1);
INSERT INTO marque VALUES (6, 'Coca Cola Light', 4, 'FR', 1);
INSERT INTO marque VALUES (7, 'Coke', 4, 'FR', 2);
INSERT INTO marque VALUES (8, 'Sprite', 4, 'FR', 2);
INSERT INTO marque VALUES (9, 'Coca Cola', 4, 'UK', 1);
INSERT INTO marque VALUES (10, 'Coca Cola Light', 4, 'UK', 1);
INSERT INTO marque VALUES (11, 'Coke', 4, 'UK', 1);
INSERT INTO marque VALUES (12, 'Sprite', 4, 'UK', 1);
INSERT INTO marque VALUES (13, 'Coca Cola', 4, 'DE', 3);
INSERT INTO marque VALUES (14, 'Coca Cola Light', 4, 'DE', 3);
INSERT INTO marque VALUES (15, 'Coke', 4, 'DE', 3);
INSERT INTO marque VALUES (16, 'Sprite', 4, 'DE', 3);
INSERT INTO marque VALUES (17, 'KOKE', 4, 'DE', 3);
INSERT INTO marque VALUES (18, 'Cola', 4, 'FR', 2);
INSERT INTO marque VALUES (19, 'Pepsi Cola', 4, 'US', 46);
INSERT INTO marque VALUES (20, 'PEPSI', 4, 'US', 46);
INSERT INTO marque VALUES (21, 'Schweepes', 4, 'US', 46);
INSERT INTO marque VALUES (22, 'Pepsi Cola', 4, 'FR', 48);
INSERT INTO marque VALUES (23, 'PEPSI', 4, 'FR', 48);
INSERT INTO marque VALUES (24, 'Schweepes', 4, 'FR', 46);
INSERT INTO marque VALUES (25, 'Pepsi Cola', 4, 'DE', 49);
INSERT INTO marque VALUES (26, 'PEPSI', 4, 'DE', 49);
INSERT INTO marque VALUES (27, 'Orangina', 4, 'FR', 48);
INSERT INTO marque VALUES (28, 'Orangina', 4, 'US', 48);
INSERT INTO marque VALUES (29, 'Orangina', 4, 'DE', 48);
INSERT INTO marque VALUES (30, 'Orangina', 4, 'UK', 48);
INSERT INTO marque VALUES (31, 'Danone', 4, 'FR', 47);
INSERT INTO marque VALUES (32, 'Danone', 4, 'US', 47);
INSERT INTO marque VALUES (33, 'Danone', 4, 'DE', 47);
INSERT INTO marque VALUES (34, 'Danone', 4, 'UK', 47);
INSERT INTO marque VALUES (35, 'Dune', 4, 'FR', 47);
INSERT INTO marque VALUES (36, 'Shalimar', 1, 'FR', 26);
INSERT INTO marque VALUES (37, 'Shalimar', 1, 'US', 26);
INSERT INTO marque VALUES (38, 'Shalimar', 1, 'DE', 26);
INSERT INTO marque VALUES (39, 'Shalimar', 1, 'UK', 26);
INSERT INTO marque VALUES (40, 'Passion', 1, 'FR', 26);
INSERT INTO marque VALUES (41, 'Passion', 1, 'US', 26);
INSERT INTO marque VALUES (42, 'Passion', 1, 'DE', 26);
INSERT INTO marque VALUES (43, 'Passion', 1, 'UK', 26);
INSERT INTO marque VALUES (44, 'Dune', 1, 'FR', 20);
INSERT INTO marque VALUES (45, 'Dune', 1, 'US', 20);
INSERT INTO marque VALUES (46, 'Dune', 1, 'DE', 20);
INSERT INTO marque VALUES (47, 'Miss Dior', 1, 'FR', 20);
INSERT INTO marque VALUES (48, 'Miss Dior', 1, 'US', 20);
INSERT INTO marque VALUES (49, 'Miss Dior', 1, 'DE', 20);
INSERT INTO marque VALUES (50, 'Miss Dior', 1, 'UK', 20);
INSERT INTO marque VALUES (51, 'Miss Dior', 1, 'MX', 50);
INSERT INTO marque VALUES (52, 'Dune', 1, 'MX', 50);
INSERT INTO marque VALUES (53, 'ORACLE', 6, 'FR', 10);
INSERT INTO marque VALUES (54, 'ORACLE', 6, 'US', 9);
INSERT INTO marque VALUES (55, 'ORACLE', 6, 'DE', 12);
INSERT INTO marque VALUES (56, 'ORACLE', 6, 'UK', 11);
INSERT INTO marque VALUES (57, 'ORACLE7', 6, 'FR', 9);
INSERT INTO marque VALUES (58, 'ORACLE7', 6, 'US', 9);
INSERT INTO marque VALUES (59, 'ORACLE7', 6, 'DE', 9);
INSERT INTO marque VALUES (60, 'ORACLE7', 6, 'UK', 9);
INSERT INTO marque VALUES (61, 'ORACLE', 11, 'FR', 26);
INSERT INTO marque VALUES (62, 'Dune', 11, 'FR', 20);
INSERT INTO marque VALUES (63, 'Dune', 11, 'US', 28);
INSERT INTO marque VALUES (64, 'Dune', 11, 'DE', 20);
INSERT INTO marque VALUES (65, 'Dune', 11, 'UK', 20);
INSERT INTO marque VALUES (66, 'Lanvin', 11, 'FR', 21);
INSERT INTO marque VALUES (67, 'Lanvin', 11, 'US', 21);
INSERT INTO marque VALUES (68, 'Lanvin', 11, 'DE', 21);
INSERT INTO marque VALUES (69, 'Lanvin', 11, 'UK', 21);
INSERT INTO marque VALUES (70, 'Coup de Coeur', 11, 'MX', 50);
INSERT INTO marque VALUES (71, 'Exorcyl', 10, 'FR', 27);
INSERT INTO marque VALUES (72, 'Exorcyl', 10, 'US', 27);
INSERT INTO marque VALUES (73, 'Exorcyl', 10, 'DE', 31);
INSERT INTO marque VALUES (74, 'Exorcyl', 10, 'UK', 27);
INSERT INTO marque VALUES (75, 'Exorcyl', 10, 'MX', 27);
INSERT INTO marque VALUES (76, 'Drobsol', 10, 'FR', 27);
INSERT INTO marque VALUES (77, 'Drobsol', 10, 'US', 27);
INSERT INTO marque VALUES (78, 'Drobsol', 10, 'DE', 31);
INSERT INTO marque VALUES (79, 'Drobsol', 10, 'UK', 27);
INSERT INTO marque VALUES (80, 'Drobsol', 10, 'MX', 27);
INSERT INTO marque VALUES (81, 'Pepsi Cola', 4, 'UK', 46);
INSERT INTO marque VALUES (82, 'PEPSI', 4, 'UK', 46);
INSERT INTO marque VALUES (83, 'Schweepes', 4, 'UK', 46);
INSERT INTO marque VALUES (84, 'Coup de Coeur', 11, 'FR', 21);
INSERT INTO marque VALUES (85, 'Coup de Coeur', 11, 'US', 21);
INSERT INTO marque VALUES (86, 'Coup de Coeur', 11, 'DE', 21);
INSERT INTO marque VALUES (87, 'Coup de Coeur', 11, 'UK', 21);
INSERT INTO marque VALUES (88, 'Cortisol', 10, 'FR', 31);
INSERT INTO marque VALUES (89, 'Cortisol', 10, 'US', 31);
INSERT INTO marque VALUES (90, 'Cortisol', 10, 'DE', 31);
INSERT INTO marque VALUES (91, 'Cortislo', 10, 'UK', 31);
INSERT INTO marque VALUES (92, 'Cortisol', 10, 'MX', 31);


--
-- TOC entry 3169 (class 0 OID 16560)
-- Dependencies: 199
-- Data for Name: pays; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO pays VALUES ('AF', 'Afghanistan');
INSERT INTO pays VALUES ('AL', 'Albania');
INSERT INTO pays VALUES ('DZ', 'Algeria');
INSERT INTO pays VALUES ('AS', 'American Samoa');
INSERT INTO pays VALUES ('AD', 'Andorra');
INSERT INTO pays VALUES ('AO', 'Angola');
INSERT INTO pays VALUES ('AI', 'Anguilla');
INSERT INTO pays VALUES ('AQ', 'Antarctica');
INSERT INTO pays VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO pays VALUES ('AR', 'Argentina');
INSERT INTO pays VALUES ('AM', 'Armenia');
INSERT INTO pays VALUES ('AW', 'Aruba');
INSERT INTO pays VALUES ('AU', 'Australia');
INSERT INTO pays VALUES ('AT', 'Austria');
INSERT INTO pays VALUES ('AZ', 'Azerbaijan');
INSERT INTO pays VALUES ('BS', 'Bahamas');
INSERT INTO pays VALUES ('BH', 'Bahrain');
INSERT INTO pays VALUES ('BD', 'Bangladesh');
INSERT INTO pays VALUES ('BB', 'Barbados');
INSERT INTO pays VALUES ('BY', 'Belarus');
INSERT INTO pays VALUES ('BE', 'Belgium');
INSERT INTO pays VALUES ('BZ', 'Belize');
INSERT INTO pays VALUES ('BJ', 'Benin');
INSERT INTO pays VALUES ('BM', 'Bermuda');
INSERT INTO pays VALUES ('BT', 'Bhutan');
INSERT INTO pays VALUES ('BO', 'Bolivia');
INSERT INTO pays VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO pays VALUES ('BW', 'Botswana');
INSERT INTO pays VALUES ('BV', 'Bouvet Island');
INSERT INTO pays VALUES ('BR', 'Brazil');
INSERT INTO pays VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO pays VALUES ('BN', 'Brunei Darussalam');
INSERT INTO pays VALUES ('BG', 'Bulgaria');
INSERT INTO pays VALUES ('BF', 'Burkina Faso');
INSERT INTO pays VALUES ('BI', 'Burundi');
INSERT INTO pays VALUES ('KH', 'Cambodia');
INSERT INTO pays VALUES ('CM', 'Cameroon');
INSERT INTO pays VALUES ('CA', 'Canada');
INSERT INTO pays VALUES ('CV', 'Cape Verde');
INSERT INTO pays VALUES ('KY', 'Cayman Islands');
INSERT INTO pays VALUES ('CF', 'Central African Republic');
INSERT INTO pays VALUES ('TD', 'Chad');
INSERT INTO pays VALUES ('NU', 'Niue');
INSERT INTO pays VALUES ('CL', 'Chile');
INSERT INTO pays VALUES ('CN', 'China');
INSERT INTO pays VALUES ('CX', 'Christmas Island');
INSERT INTO pays VALUES ('CC', 'Cocos (Keeling Islands)');
INSERT INTO pays VALUES ('CO', 'Colombia');
INSERT INTO pays VALUES ('KM', 'Comoros');
INSERT INTO pays VALUES ('CG', 'Congo');
INSERT INTO pays VALUES ('CK', 'Cook Islands');
INSERT INTO pays VALUES ('CR', 'Costa Rica');
INSERT INTO pays VALUES ('CI', 'Cote D''Ivoire (Ivory Coast)');
INSERT INTO pays VALUES ('HR', 'Croatia (Hrvatska');
INSERT INTO pays VALUES ('CU', 'Cuba');
INSERT INTO pays VALUES ('CY', 'Cyprus');
INSERT INTO pays VALUES ('CZ', 'Czech Republic');
INSERT INTO pays VALUES ('DK', 'Denmark');
INSERT INTO pays VALUES ('DJ', 'Djibouti');
INSERT INTO pays VALUES ('DM', 'Dominica');
INSERT INTO pays VALUES ('DO', 'Dominican Republic');
INSERT INTO pays VALUES ('TP', 'East Timor');
INSERT INTO pays VALUES ('EC', 'Ecuador');
INSERT INTO pays VALUES ('EG', 'Egypt');
INSERT INTO pays VALUES ('SV', 'El Salvador');
INSERT INTO pays VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO pays VALUES ('ER', 'Eritrea');
INSERT INTO pays VALUES ('EE', 'Estonia');
INSERT INTO pays VALUES ('ET', 'Ethiopia');
INSERT INTO pays VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO pays VALUES ('FO', 'Faroe Islands');
INSERT INTO pays VALUES ('FJ', 'Fiji');
INSERT INTO pays VALUES ('FI', 'Finland');
INSERT INTO pays VALUES ('FX', 'FR, Metropolitan');
INSERT INTO pays VALUES ('GF', 'French Guiana');
INSERT INTO pays VALUES ('PF', 'French Polynesia');
INSERT INTO pays VALUES ('TF', 'French Southern Territories');
INSERT INTO pays VALUES ('GA', 'Gabon');
INSERT INTO pays VALUES ('GM', 'Gambia');
INSERT INTO pays VALUES ('GE', 'Georgia');
INSERT INTO pays VALUES ('GH', 'Ghana');
INSERT INTO pays VALUES ('GI', 'Gibraltar');
INSERT INTO pays VALUES ('GR', 'Greece');
INSERT INTO pays VALUES ('GL', 'Greenland');
INSERT INTO pays VALUES ('GD', 'Grenada');
INSERT INTO pays VALUES ('GP', 'Guadeloupe');
INSERT INTO pays VALUES ('GU', 'Guam');
INSERT INTO pays VALUES ('GT', 'Guatemala');
INSERT INTO pays VALUES ('GN', 'Guinea');
INSERT INTO pays VALUES ('GW', 'Guinea-Bissau');
INSERT INTO pays VALUES ('GY', 'Guyana');
INSERT INTO pays VALUES ('HT', 'Haiti');
INSERT INTO pays VALUES ('HM', 'Heard and McDonald Islands');
INSERT INTO pays VALUES ('HN', 'Honduras');
INSERT INTO pays VALUES ('HK', 'Hong Kong');
INSERT INTO pays VALUES ('HU', 'Hungary');
INSERT INTO pays VALUES ('IS', 'Iceland');
INSERT INTO pays VALUES ('IN', 'India');
INSERT INTO pays VALUES ('ID', 'Indonesia');
INSERT INTO pays VALUES ('IR', 'Iran');
INSERT INTO pays VALUES ('IQ', 'Iraq');
INSERT INTO pays VALUES ('IE', 'Ireland');
INSERT INTO pays VALUES ('IL', 'Israel');
INSERT INTO pays VALUES ('IT', 'Italy');
INSERT INTO pays VALUES ('JM', 'Jamaica');
INSERT INTO pays VALUES ('JP', 'Japan');
INSERT INTO pays VALUES ('JO', 'Jordan');
INSERT INTO pays VALUES ('KZ', 'Kazakhstan');
INSERT INTO pays VALUES ('KE', 'Kenya');
INSERT INTO pays VALUES ('KI', 'Kiribati');
INSERT INTO pays VALUES ('KP', 'Korea (North)');
INSERT INTO pays VALUES ('KR', 'Korea (South)');
INSERT INTO pays VALUES ('KW', 'Kuwait');
INSERT INTO pays VALUES ('KG', 'Kyrgyzstan');
INSERT INTO pays VALUES ('LA', 'Laos');
INSERT INTO pays VALUES ('LV', 'Latvia');
INSERT INTO pays VALUES ('LB', 'Lebanon');
INSERT INTO pays VALUES ('LS', 'Lesotho');
INSERT INTO pays VALUES ('LR', 'Liberia');
INSERT INTO pays VALUES ('LY', 'Libya');
INSERT INTO pays VALUES ('LI', 'Liechtenstein');
INSERT INTO pays VALUES ('LT', 'Lithuania');
INSERT INTO pays VALUES ('LU', 'Luxembourg');
INSERT INTO pays VALUES ('MO', 'Macau');
INSERT INTO pays VALUES ('MK', 'Macedonia');
INSERT INTO pays VALUES ('MG', 'Madagascar');
INSERT INTO pays VALUES ('MW', 'Malawi');
INSERT INTO pays VALUES ('MY', 'Malaysia');
INSERT INTO pays VALUES ('MV', 'Maldives');
INSERT INTO pays VALUES ('ML', 'Mali');
INSERT INTO pays VALUES ('MT', 'Malta');
INSERT INTO pays VALUES ('MH', 'Marshall Islands');
INSERT INTO pays VALUES ('MQ', 'Martinique');
INSERT INTO pays VALUES ('MR', 'Mauritania');
INSERT INTO pays VALUES ('MU', 'Mauritius');
INSERT INTO pays VALUES ('YT', 'Mayotte');
INSERT INTO pays VALUES ('MX', 'Mexico');
INSERT INTO pays VALUES ('FM', 'Micronesia');
INSERT INTO pays VALUES ('MD', 'Moldova');
INSERT INTO pays VALUES ('MC', 'Monaco');
INSERT INTO pays VALUES ('MN', 'Mongolia');
INSERT INTO pays VALUES ('MS', 'Montserrat');
INSERT INTO pays VALUES ('MA', 'Morocco');
INSERT INTO pays VALUES ('MZ', 'Mozambique');
INSERT INTO pays VALUES ('MM', 'Myanmar');
INSERT INTO pays VALUES ('NA', 'Namibia');
INSERT INTO pays VALUES ('NR', 'Nauru');
INSERT INTO pays VALUES ('NP', 'Nepal');
INSERT INTO pays VALUES ('NL', 'Netherlands');
INSERT INTO pays VALUES ('AN', 'Netherlands Antilles');
INSERT INTO pays VALUES ('NC', 'New Caledonia');
INSERT INTO pays VALUES ('NZ', 'New Zealand');
INSERT INTO pays VALUES ('NI', 'Nicaragua');
INSERT INTO pays VALUES ('NE', 'Niger');
INSERT INTO pays VALUES ('NG', 'Nigeria');
INSERT INTO pays VALUES ('NF', 'Norfolk Island');
INSERT INTO pays VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO pays VALUES ('NO', 'Norway');
INSERT INTO pays VALUES ('OM', 'Oman');
INSERT INTO pays VALUES ('PK', 'Pakistan');
INSERT INTO pays VALUES ('PW', 'Palau');
INSERT INTO pays VALUES ('PA', 'Panama');
INSERT INTO pays VALUES ('PG', 'Papua New Guinea');
INSERT INTO pays VALUES ('PY', 'Paraguay');
INSERT INTO pays VALUES ('PE', 'Peru');
INSERT INTO pays VALUES ('PH', 'Philippines');
INSERT INTO pays VALUES ('PN', 'Pitcairn');
INSERT INTO pays VALUES ('PL', 'Poland');
INSERT INTO pays VALUES ('PT', 'Portugal');
INSERT INTO pays VALUES ('PR', 'Puerto Rico');
INSERT INTO pays VALUES ('QA', 'Qatar');
INSERT INTO pays VALUES ('RE', 'Reunion');
INSERT INTO pays VALUES ('RO', 'Romania');
INSERT INTO pays VALUES ('RU', 'Russian Federation');
INSERT INTO pays VALUES ('RW', 'Rwanda');
INSERT INTO pays VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO pays VALUES ('LC', 'Saint Lucia');
INSERT INTO pays VALUES ('VC', 'Saint Vincent and The Grenadines');
INSERT INTO pays VALUES ('WS', 'Samoa');
INSERT INTO pays VALUES ('SM', 'San Marino');
INSERT INTO pays VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO pays VALUES ('SA', 'Saudi Arabia');
INSERT INTO pays VALUES ('SN', 'Senegal');
INSERT INTO pays VALUES ('SC', 'Seychelles');
INSERT INTO pays VALUES ('SL', 'Sierra Leone');
INSERT INTO pays VALUES ('SG', 'Singapore');
INSERT INTO pays VALUES ('SK', 'Slovak Republic');
INSERT INTO pays VALUES ('SI', 'Slovenia');
INSERT INTO pays VALUES ('SB', 'Solomon Islands');
INSERT INTO pays VALUES ('SO', 'Somalia');
INSERT INTO pays VALUES ('ZA', 'South Africa');
INSERT INTO pays VALUES ('GS', 'S. Georgia and S. Sandwich Isls.');
INSERT INTO pays VALUES ('ES', 'Spain');
INSERT INTO pays VALUES ('LK', 'Sri Lanka');
INSERT INTO pays VALUES ('SH', 'St. Helena');
INSERT INTO pays VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO pays VALUES ('SD', 'Sudan');
INSERT INTO pays VALUES ('SR', 'Suriname');
INSERT INTO pays VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO pays VALUES ('SZ', 'Swaziland');
INSERT INTO pays VALUES ('SE', 'Sweden');
INSERT INTO pays VALUES ('CH', 'Switzerland');
INSERT INTO pays VALUES ('SY', 'Syria');
INSERT INTO pays VALUES ('TW', 'Taiwan');
INSERT INTO pays VALUES ('TJ', 'Tajikistan');
INSERT INTO pays VALUES ('TZ', 'Tanzania');
INSERT INTO pays VALUES ('TH', 'Thailand');
INSERT INTO pays VALUES ('TG', 'Togo');
INSERT INTO pays VALUES ('TK', 'Tokelau');
INSERT INTO pays VALUES ('TO', 'Tonga');
INSERT INTO pays VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO pays VALUES ('TN', 'Tunisia');
INSERT INTO pays VALUES ('TR', 'Turkey');
INSERT INTO pays VALUES ('TM', 'Turkmenistan');
INSERT INTO pays VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO pays VALUES ('TV', 'Tuvalu');
INSERT INTO pays VALUES ('UG', 'Uganda');
INSERT INTO pays VALUES ('UA', 'Ukraine');
INSERT INTO pays VALUES ('AE', 'United Arab Emirates');
INSERT INTO pays VALUES ('UM', 'US Minor Outlying Islands');
INSERT INTO pays VALUES ('UY', 'Uruguay');
INSERT INTO pays VALUES ('UZ', 'Uzbekistan');
INSERT INTO pays VALUES ('VU', 'Vanuatu');
INSERT INTO pays VALUES ('VA', 'Vatican City State (Holy See)');
INSERT INTO pays VALUES ('VE', 'Venezuela');
INSERT INTO pays VALUES ('VN', 'Viet Nam');
INSERT INTO pays VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO pays VALUES ('VI', 'Virgin Islands (US)');
INSERT INTO pays VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO pays VALUES ('EH', 'Western Sahara');
INSERT INTO pays VALUES ('YE', 'Yemen');
INSERT INTO pays VALUES ('YU', 'Yugoslavia');
INSERT INTO pays VALUES ('ZR', 'Zaire');
INSERT INTO pays VALUES ('ZM', 'Zambia');
INSERT INTO pays VALUES ('ZW', 'Zimbabwe');
INSERT INTO pays VALUES ('DE', 'Germany');
INSERT INTO pays VALUES ('FR', 'France');
INSERT INTO pays VALUES ('UK', 'United Kingdom');
INSERT INTO pays VALUES ('US', 'United States');


--
-- TOC entry 3170 (class 0 OID 16563)
-- Dependencies: 200
-- Data for Name: societe; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO societe VALUES (1, 'Coca Cola, Inc.', 'Denver', 'US');
INSERT INTO societe VALUES (2, 'Ste. Coca Cola', 'Paris', 'FR');
INSERT INTO societe VALUES (3, 'Coca Cola Gmbh.', 'Kohln', 'DE');
INSERT INTO societe VALUES (4, 'SUN MicroSystems, Inc.', 'Mountain View', 'US');
INSERT INTO societe VALUES (5, 'Ste. SUN', 'Velizy', 'FR');
INSERT INTO societe VALUES (6, 'IBM Corp.', 'Yorktown', 'US');
INSERT INTO societe VALUES (7, 'IBM', 'Paris', 'FR');
INSERT INTO societe VALUES (8, 'IBM Ltd.', 'Manchester', 'UK');
INSERT INTO societe VALUES (9, 'ORACLE Corp.', 'Redwood City', 'US');
INSERT INTO societe VALUES (10, 'Ste. ORACLE', 'Aix-en-Pce', 'FR');
INSERT INTO societe VALUES (11, 'ORACLE Ltd.', 'Heathrow', 'UK');
INSERT INTO societe VALUES (12, 'ORACLE Gmbh.', 'Hamburg', 'DE');
INSERT INTO societe VALUES (13, 'VERILOG Compy.', 'New-York City', 'US');
INSERT INTO societe VALUES (14, 'Cie. VERILOG', 'Toulouse', 'FR');
INSERT INTO societe VALUES (15, 'AIRBUS Ind.', 'Heathrow', 'UK');
INSERT INTO societe VALUES (16, 'AIRBUS  Gmbh.', 'Hamburg', 'DE');
INSERT INTO societe VALUES (17, 'DASSAULT Corp.', 'Dallas', 'US');
INSERT INTO societe VALUES (18, 'Ste. Marcel Dassault', 'Boulogne', 'FR');
INSERT INTO societe VALUES (19, 'Ste. Electronique Serge Dassault', 'Boulogne', 'FR');
INSERT INTO societe VALUES (20, 'Ste.Christian DIOR', 'Paris', 'FR');
INSERT INTO societe VALUES (21, 'Ste. L.V.H.M.', 'Paris', 'FR');
INSERT INTO societe VALUES (22, 'Ste. OREAL', 'Paris', 'FR');
INSERT INTO societe VALUES (23, 'Ste. Boussac', 'Paris', 'FR');
INSERT INTO societe VALUES (24, 'Ste. LANVIN', 'Paris', 'FR');
INSERT INTO societe VALUES (25, 'Ste. Courreges', 'Paris', 'FR');
INSERT INTO societe VALUES (26, 'Ste. GUERLAIN', 'Grasse', 'FR');
INSERT INTO societe VALUES (27, 'Lab. Roussel', 'Paris', 'FR');
INSERT INTO societe VALUES (28, 'Helena Rubinstein Ltd.', 'New-York City', 'US');
INSERT INTO societe VALUES (29, 'La Roche Posay', 'Limoges', 'FR');
INSERT INTO societe VALUES (30, 'UNILEVER Corp.', 'Heathrow', 'UK');
INSERT INTO societe VALUES (31, 'Hoescht  Gmbh.', 'Hamburg', 'DE');
INSERT INTO societe VALUES (32, 'BMW  Gmbh.', 'Hamburg', 'DE');
INSERT INTO societe VALUES (33, 'Mercedez-Benz  Gmbh.', 'Munchen', 'DE');
INSERT INTO societe VALUES (34, 'FORD Ltd.', 'New-York City', 'US');
INSERT INTO societe VALUES (35, 'CHRYSLER Ltd.', 'Detroit', 'US');
INSERT INTO societe VALUES (36, 'S.A. Renault', 'Boulogne', 'FR');
INSERT INTO societe VALUES (37, 'S.A. PSA', 'PAris', 'FR');
INSERT INTO societe VALUES (38, 'Rolls Royce Ltd.', 'London', 'UK');
INSERT INTO societe VALUES (39, 'ROVER Ltd.', 'London', 'UK');
INSERT INTO societe VALUES (40, 'Boeing Corp.', 'Denver', 'US');
INSERT INTO societe VALUES (41, 'Ste. Boeing', 'Paris', 'FR');
INSERT INTO societe VALUES (42, 'Boeing  Ltd.', 'Heathrow', 'UK');
INSERT INTO societe VALUES (43, 'Boeing  Gmbh.', 'Munchen', 'DE');
INSERT INTO societe VALUES (44, 'AIRBUS Corp.', 'Houston', 'US');
INSERT INTO societe VALUES (45, 'AIRBUS Industrie', 'Toulouse', 'FR');
INSERT INTO societe VALUES (46, 'PEPSI Inc.', 'Houston', 'US');
INSERT INTO societe VALUES (47, 'Ste. Danone', 'Lyon', 'FR');
INSERT INTO societe VALUES (48, 'Ste. Orangina', 'Lyon', 'FR');
INSERT INTO societe VALUES (49, 'Pepsi Gmbh.', 'Aichen', 'DE');
INSERT INTO societe VALUES (50, 'Soc. Perfumes y Trajes', 'Mexico', 'MX');


--
-- TOC entry 3171 (class 0 OID 16566)
-- Dependencies: 201
-- Data for Name: vente; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO vente VALUES (69, 24, 21, '1994-01-01');
INSERT INTO vente VALUES (12, 46, 1, '1982-01-01');
INSERT INTO vente VALUES (56, 9, 11, '1985-01-01');
INSERT INTO vente VALUES (22, 46, 48, '1987-01-01');
INSERT INTO vente VALUES (23, 46, 48, '1987-01-01');
INSERT INTO vente VALUES (66, 24, 21, '1992-01-01');
INSERT INTO vente VALUES (8, 46, 2, '1980-01-01');
INSERT INTO vente VALUES (53, 14, 10, '1987-01-01');
INSERT INTO vente VALUES (45, 28, 20, '2050-01-01');
INSERT INTO vente VALUES (67, 28, 21, '1992-01-01');
INSERT INTO vente VALUES (28, 46, 1, '1975-01-01');
INSERT INTO vente VALUES (28, 1, 48, '1981-01-01');
INSERT INTO vente VALUES (41, 28, 26, '1972-01-01');
INSERT INTO vente VALUES (4, 46, 1, '1983-01-01');
INSERT INTO vente VALUES (13, 1, 3, '2050-01-01');
INSERT INTO vente VALUES (25, 46, 49, '2051-01-01');
INSERT INTO vente VALUES (26, 46, 49, '2051-01-01');
INSERT INTO vente VALUES (67, 24, 21, '2037-01-01');
INSERT INTO vente VALUES (73, 27, 31, '1978-01-01');
INSERT INTO vente VALUES (15, 1, 3, '1980-01-01');
INSERT INTO vente VALUES (17, 1, 3, '1980-01-01');
INSERT INTO vente VALUES (16, 46, 3, '1980-01-01');
INSERT INTO vente VALUES (78, 27, 31, '1987-01-01');
INSERT INTO vente VALUES (14, 1, 3, '1986-01-01');
INSERT INTO vente VALUES (55, 9, 12, '1986-01-01');
INSERT INTO vente VALUES (61, 9, 26, '1994-01-01');
INSERT INTO vente VALUES (30, 48, 49, '2068-03-07');
INSERT INTO vente VALUES (30, 12, 27, '2068-03-07');
INSERT INTO vente VALUES (3, 5, 7, '1980-02-05');



-- Completed on 2019-09-13 10:56:29 CEST

--
-- PostgreSQL database dump complete
--
COMMIT;
